# Generated by Django 5.1.4 on 2024-12-30 12:17

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='AR'),
        ),
    ]
