# Generated by Django 5.1.4 on 2024-12-30 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0003_cliente_notas_alter_cliente_apellidos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
